name: Check for breaking changes

on:
  workflow_dispatch:

jobs:
  ubuntu_build:
    name: Build without tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 120
    concurrency: 
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' 
          java-version: '11'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build repo with Gradle and publish maven local
        run: |
          ./gradlew build publishToMavenLocal -x test --max-workers=2 --scan --no-daemon
          cd ..
      
      - name: Checkout distribution
        uses: actions/checkout@v2
        with:
          repository: ballerina-platform/ballerina-distribution
          
      - name: Build dist with Gradle
        env:
          packagePAT: ${{ secrets.packagePAT }}
          packageUser: ${{ secrets.packageUser }}
        run: |
          pwd
          ./gradlew build  -x test
          
      - name: Unzip distribution zip
        run: |
          cd ./ballerina/build/distributions/
          unzip *SNAPSHOT-swan-lake-linux.zip -d .
          
      - name: Check bal command
        run: |
          cd ./ballerina/build/distributions/*SNAPSHOT-swan-lake-linux/bin
          ./bal -v
      
       
