name: Check for breaking changes

on:
  workflow_dispatch:

jobs:
  ubuntu_build:
    name: Build without tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 120
    concurrency: 
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' 
          java-version: '11'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build repo with Gradle and publish maven local
        run: |
          ./gradlew build publishToMavenLocal -x test --max-workers=2 --scan --no-daemon
          cd ..
      
      - name: Checkout distribution
        uses: actions/checkout@v2
        with:
          repository: ballerina-platform/ballerina-distribution
          
      - name: Build dist with Gradle
        env:
          packagePAT: ${{ secrets.packagePAT }}
          packageUser: ${{ github.actor }}
          # packageUser: ${{ github.actor }}
          # packagePAT: ${{ secrets.GITHUB_TOKEN }}
          # devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
          # TEST_MODE_ACTIVE: true
        run: |
          pwd
          ./gradlew build  -x test
      
      - name: Upload distribution
        uses: actions/upload-artifact@v3
        with:
          name: test-distriubtion
          path: ./ballerina/build/distributions/*SNAPSHOT-swan-lake-linux.zip
          
#   check_connectors:
#     name: Check for breaking changes in ballerinax connectors
#     runs-on: ubuntu-latest
#     needs: ubuntu_build
#     steps:

#       - name: checkout connector
#         uses: actions/checkout@v2
#         with:
#           repository: ballerina-platform/module-ballerinax-twitter
          
#       - name: Set up JDK 11
#         uses: actions/setup-java@v1
#         with:
#           java-version: 11
            
#       - name: Grant execute permission for gradlew
#         run: chmod +x gradlew
        
#       - name: Dowload archived distribution
#         uses: actions/download-artifact@v3
#         with:
#           name: test-distriubtion
          
#       - name: Unzip distribution zip
#         run: |
#           unzip *SNAPSHOT-swan-lake-linux.zip -d ./distribution
#           ls ./distribution
          
#       - name: Check bal command
#         run: |
#           chmod +x ./distribution/*linux/bin/bal
#           ./distribution/*linux/bin/bal -v
        
#       - name: build connector
#         run: ./distribution/*linux/bin/bal build ./twitter
        
  check_stdlib:
    name: Check for breaking changes in level 8 stdlib modules
    strategy:
      matrix:
        stdlibs: [java.jdbc, mssql, mysql, oracledb, postgresql]
    runs-on: ubuntu-latest
    needs: ubuntu_build
    steps:

      - name: checkout connector
        uses: actions/checkout@v2
        with:
          repository: ballerina-platform/module-ballerinax-${{matrix.stdlibs}}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Dowload archived distribution
        uses: actions/download-artifact@v3
        with:
          name: test-distriubtion

      - name: Unzip distribution zip
        run: |
          unzip *SNAPSHOT-swan-lake-linux.zip -d ./distribution
          ls ./distribution

      - name: Check bal command
        run: |
          chmod +x ./distribution/*linux/bin/bal
#          ./distribution/*linux/bin/bal -v
      
      - name: Set bal path
        run: | 
          cd ./distribution/*linux/bin
          echo $(pwd) >> $GITHUB_PATH
          bal -v

      - name: build stdlib
        run: ./gradlew clean build


