name: CCheck for breaking changes in ballerinax connectors
on: workflow_dispatch

jobs:
  check_breaking_changes_ballerina_extended_library:
    strategy:
      matrix:
        modules:
          [
            choreo,
            jaeger,
            java.jdbc,
            kafka,
            mssql,
            mysql,
            nats,
            oracledb,
            postgresql,
            prometheus,
            rabbitmq,
            stan,
          ]
    runs-on: ubuntu-latest
    name: Check ${{matrix.modules}} build
    steps:
      - name: Download ballerina distribution
        run: wget -O distribution.deb https://dist.ballerina.io/downloads/2201.0.3/ballerina-2201.0.3-swan-lake-linux-x64.deb

      - name: Install ballerina distribution
        run: sudo dpkg -i distribution.deb

      - name: checkout connector
        uses: actions/checkout@v2
        with:
          repository: ballerina-platform/module-ballerinax-${{matrix.modules}}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build stdlib
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build
