name: CCheck for breaking changes in ballerinax connectors
on: 
  workflow_dispatch
        
jobs:
  build_ballerina_extended_library_modules_with_gradle:
    strategy:
      fail-fast: false
      matrix:
        modules: [choreo, jaeger, java.jdbc, kafka, mssql, mysql, nats, oracledb, postgresql, prometheus, rabbitmq, stan]
    runs-on: ubuntu-latest
    name: Check ${{matrix.modules}} build (1)
    steps:
      - name: Download ballerina distribution
        run: wget -O distribution.deb https://dist.ballerina.io/downloads/2201.0.3/ballerina-2201.0.3-swan-lake-linux-x64.deb

      - name: Install ballerina distribution
        run: sudo dpkg -i distribution.deb

      - name: checkout connector
        uses: actions/checkout@v2
        with:
          repository: ballerina-platform/module-ballerinax-${{matrix.modules}}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build stdlib
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build
        
  build_ballerinax_connector_modules_with_gradle:
      strategy:
        fail-fast: false
        matrix:
          modules: [azure.functions, cdata.connect, datamapper, jaeger, prometheus, snowflake]
      runs-on: ubuntu-latest
      name: Check ${{matrix.modules}} build (2)
      steps:
        - name: Download ballerina distribution
          run: wget -O distribution.deb https://dist.ballerina.io/downloads/2201.0.3/ballerina-2201.0.3-swan-lake-linux-x64.deb

        - name: Install ballerina distribution
          run: sudo dpkg -i distribution.deb

        - name: checkout connector
          uses: actions/checkout@v2
          with:
            repository: ballerina-platform/module-ballerinax-${{matrix.modules}}

        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: build module
          env:
            packageUser: ${{ github.actor }}
            packagePAT: ${{ secrets.GITHUB_TOKEN }}
          run: ./gradlew clean build
          
  build_ballerinax_connector_modules_with_gradle_and_bal:
      strategy:
        fail-fast: false
        matrix:
          include: 
            - modules: aws.s3 
              ballerina_directory: s3
            - modules: aws.sqs 
              ballerina_directory: sqs
            - modules: aws.ses 
              ballerina_directory: ses
            - modules: azure-cosmosdb 
              ballerina_directory: cosmosdb
            - modules: azure-storage-service 
              ballerina_directory: storageservice
            - modules: azure-service-bus 
              ballerina_directory: asb-ballerina
            - modules: azure.eventhub 
              ballerina_directory: eventhub
            - modules: googleapis.drive 
              ballerina_directory: drive
            - modules: googleapis.people 
              ballerina_directory: gpeople
            - modules: googleapis.sheets 
              ballerina_directory: gsheet
            - modules: googleapis.calendar 
              ballerina_directory: calendar
            - modules: googleapis.gmail 
              ballerina_directory: gmail
            - modules: github
              ballerina_directory: github
            - modules: microsoft.outlook.mail 
              ballerina_directory: outlookmail
            - modules: microsoft.onenote 
              ballerina_directory: onenote
            - modules: microsoft.excel 
              ballerina_directory: excel
            - modules: microsoft.outlook.calendar 
              ballerina_directory: calendar
            - modules: microsoft.onedrive 
              ballerina_directory: onedrive
            - modules: microsoft.teams 
              ballerina_directory: teams
            - modules: mongodb 
              ballerina_directory: mongodb
            - modules: netsuite 
              ballerina_directory: netsuite
            - modules: slack 
              ballerina_directory: slack
            - modules: sfdc 
              ballerina_directory: salesforce
            - modules: twitter 
              ballerina_directory: twitter
            - modules: twilio 
              ballerina_directory: twilio

      runs-on: ubuntu-latest
      name: Check ${{matrix.modules}} build (3)
      steps:
        - name: Download ballerina distribution
          run: wget -O distribution.deb https://dist.ballerina.io/downloads/2201.0.3/ballerina-2201.0.3-swan-lake-linux-x64.deb

        - name: Install ballerina distribution
          run: sudo dpkg -i distribution.deb

        - name: checkout connector
          uses: actions/checkout@v2
          with:
            repository: ballerina-platform/module-ballerinax-${{matrix.modules}}

        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: build module with gradle
          env:
            packageUser: ${{ github.actor }}
            packagePAT: ${{ secrets.GITHUB_TOKEN }}
          run: ./gradlew clean build
          
        - name: test and build with ballerina
          run: |
            bal build ${{matrix.ballerina_directory}}
#            bal test ${{matrix.ballerina_directory}}
          
            
  build_ballerinax_connector_modules_with_bal:
      strategy:
        fail-fast: false
        matrix:
          include: 
            - modules: aws.dynamodb
            - modules: aws.simpledb
            - modules: aws.sns 
              ballerina_directory: sns
            - modules: cdata.connect.driver
            - modules: azure.ad 
              ballerina_directory: aad
            - modules: mysql.driver
            - modules: mssql.driver
            - modules: oracledb.driver
            - modules: postgresql.driver
            - modules: peoplehr 
              ballerina_directory: peoplehr
            - modules: snowflake.driver


      runs-on: ubuntu-latest
      name: Check ${{matrix.modules}} build (4)
      steps:
        - name: Download ballerina distribution
          run: wget -O distribution.deb https://dist.ballerina.io/downloads/2201.0.3/ballerina-2201.0.3-swan-lake-linux-x64.deb

        - name: Install ballerina distribution
          run: sudo dpkg -i distribution.deb

        - name: checkout connector
          uses: actions/checkout@v2
          with:
            repository: ballerina-platform/module-ballerinax-${{matrix.modules}}

        - name: test and build with ballerina
          run: |
            bal build ${{matrix.ballerina_directory}}
#            bal test ${{matrix.ballerina_directory}}



