name: Trigger ballerinax connector build
on:
  workflow_dispatch:
    inputs:
      artifact:
        description: "artifact id"
        required: true

jobs:
  trigger_repository_disptach_in_ballerinax:
    strategy:
      fail-fast: false
      matrix:
        modules: [twitter]
    name: Trigger ballerinax connector builds
    runs-on: ubuntu-latest
    steps:

      - name: disptch build request
        run: |
          curl --request \
          POST 'https://api.github.com/repos/mohamedsabthar/module-ballerinax-${{matrix.modules}}/dispatches' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: token ${{secrets.GITHUB_TOKEN}}' \
          --data-raw '{
              "event_type":"check_connector_for_breaking_changes",
              "client_payload":{
                "artifact":${{github.event.inputs.artifact}}
                }
          }'
